create table if not exists public.projects (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  type text not null check (type in ('drawing', 'comic')),
  thumbnail_url text,
  project_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_user_updated_idx on public.projects (user_id, updated_at desc);

alter table public.projects enable row level security;
grant select, insert, update, delete on table public.projects to authenticated;

create policy "projects_select_own" on public.projects for select to authenticated
using ((select auth.uid()) = user_id);
create policy "projects_insert_own" on public.projects for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "projects_update_own" on public.projects for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "projects_delete_own" on public.projects for delete to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.image_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('search', 'generate')),
  created_at timestamptz not null default now()
);

create index if not exists image_usage_user_kind_created_idx on public.image_usage (user_id, kind, created_at desc);
alter table public.image_usage enable row level security;
grant select, insert on table public.image_usage to authenticated;
grant usage, select on sequence public.image_usage_id_seq to authenticated;

create policy "image_usage_select_own" on public.image_usage for select to authenticated
using ((select auth.uid()) = user_id);
create policy "image_usage_insert_own" on public.image_usage for insert to authenticated
with check ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('project-assets', 'project-assets', false, 15728640, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "project_assets_select_own" on storage.objects for select to authenticated
using (bucket_id = 'project-assets' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "project_assets_insert_own" on storage.objects for insert to authenticated
with check (bucket_id = 'project-assets' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "project_assets_update_own" on storage.objects for update to authenticated
using (bucket_id = 'project-assets' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'project-assets' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "project_assets_delete_own" on storage.objects for delete to authenticated
using (bucket_id = 'project-assets' and (storage.foldername(name))[1] = (select auth.uid())::text);
